# These are supported funding model platforms

github: # FTKhanFT
patreon: # FTKhanFT
open_collective: # FTKhanFT
ko_fi: # FTKhanFT
community_bridge: # FTKhanFT
liberapay: # FTKhanFT
issuehunt: # FTKhanFT
otechie: # FTKhanFT
